"""
Pydantic v2 models for the chat API.

Covers single-turn requests/responses, WebSocket streaming chunks,
and the CommandPreview structure that triggers the frontend approval gate.
"""

from __future__ import annotations

from enum import Enum
from typing import Any, Literal

from pydantic import BaseModel, Field


class RiskLevel(str, Enum):
    """Risk classification for generated Kubernetes commands."""

    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class Message(BaseModel):
    """A single conversation message."""

    role: Literal["user", "assistant", "system"]
    content: str


class CommandPreview(BaseModel):
    """Dry-run result surfaced to the frontend before command execution."""

    kubectl_command: str = Field(description="The kubectl command string generated by the agent.")
    manifest_yaml: str | None = Field(default=None, description="Raw YAML manifest, if applicable.")
    diff: str = Field(description="Unified diff output from kubectl --dry-run=server.")
    warnings: list[str] = Field(default_factory=list, description="kubectl warnings from stderr.")
    resource_name: str = Field(description="Target Kubernetes resource name.")
    resource_kind: str = Field(description="Kubernetes resource kind, e.g. Deployment.")
    risk_level: RiskLevel = Field(description="Assessed risk level for the operation.")
    is_safe: bool = Field(description="Whether the dry-run completed without errors.")


class ChatRequest(BaseModel):
    """Single-turn POST /api/chat request body."""

    message: str = Field(description="The user's natural language message.")
    cluster_context: str = Field(description="Active kubeconfig context name.")
    namespace: str = Field(default="default", description="Active Kubernetes namespace.")
    session_id: str = Field(description="Client-generated session UUID for correlation.")


class ChatResponse(BaseModel):
    """Single-turn POST /api/chat response body."""

    response: str = Field(description="The assistant's text response.")
    command_preview: CommandPreview | None = Field(
        default=None,
        description="Present when the agent produced a command requiring user approval.",
    )
    audit_event_id: str = Field(description="UUID of the audit log entry for this interaction.")


class StreamChunk(BaseModel):
    """A single WebSocket streaming chunk sent from backend to frontend."""

    type: Literal["token", "command_preview", "done", "error"]
    content: str | dict[str, Any] = Field(
        description="Token string for type=token; CommandPreview dict for type=command_preview; message string for type=done|error."
    )


class ApprovalRequest(BaseModel):
    """POST /api/chat/approve — user approves or rejects a pending command."""

    session_id: str
    audit_event_id: str
    approved: bool
    manifest_yaml: str | None = None


class ApprovalResponse(BaseModel):
    """Response to an approval request."""

    status: Literal["accepted", "rejected"]


class WSIncomingMessage(BaseModel):
    """Incoming WebSocket message from the client."""

    type: Literal["chat", "approval", "clear_context"] = Field(default="chat")
    message: str | None = None
    cluster_context: str | None = None
    namespace: str | None = Field(default="default")
    session_id: str | None = None
    approved: bool | None = None
    audit_event_id: str | None = None
