"""
KubeNova LangGraph state definition.

The KubeNovaState TypedDict is the single shared state object that flows
through every node in the StateGraph. Nodes read from it and return
partial dicts to update it; LangGraph merges updates automatically.
"""

from __future__ import annotations

from typing import TypedDict

from langchain_core.messages import BaseMessage


class KubeNovaState(TypedDict, total=False):
    """
    Shared state for the KubeNova LangGraph agent.

    All fields are optional (total=False) so individual nodes can return
    only the keys they modify. LangGraph will merge partial updates into
    the accumulated state.
    """

    messages: list[BaseMessage]
    """Accumulated conversation messages (HumanMessage, AIMessage, ToolMessage)."""

    cluster_context: str
    """Active kubeconfig context name for this session."""

    namespace: str
    """Active Kubernetes namespace for this session."""

    user_intent: str
    """The raw user message / intent text."""

    risk_level: str
    """RiskLevel enum value determined by the safety_gate node."""

    command_preview: dict | None
    """CommandPreview dict surfaced to the frontend; None until agent generates one."""

    dry_run_result: dict | None
    """DryRunResult dict from executor.dry_run_manifest(); None until run."""

    user_approved: bool
    """True once the user has approved the command via the approval endpoint."""

    incident_mode: bool
    """True when the user triggered guided incident response mode."""

    incident_findings: list[str]
    """Ordered list of findings accumulated during incident analysis."""

    error: str | None
    """Error message if any node encountered a non-fatal error."""

    audit_event_id: str | None
    """UUID of the audit log entry written at the start of the interaction."""

    session_id: str
    """Client-supplied session identifier for correlation."""

    generated_command: str | None
    """kubectl command string generated by the agent."""
